version: "3.9"
services:
  ingress:
    ports:
      - 127.0.0.1:8000:80
    image: nginx:latest
    volumes:
      - ./frontend/var/www/static/:ro 
      - ./nginx.conf:/etc/nginx/nginx.conf:ro #readonly - ro, read&write - rw

    depends on:
      - auth
      - chat
  
  auth:
    - ./authAPI/.
  chat:
    - ./chatAPI/.





